import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsOptional, IsString } from 'class-validator';

export class CheckoutBookingDto {
  @ApiProperty({
    description: 'Payment method selected by the customer',
    enum: ['UPI', 'CARD', 'NETBANK', 'WALLET', 'upi', 'card', 'netbank', 'wallet'],
    required: false,
    example: 'UPI',
  })
  @IsOptional()
  @IsEnum(['UPI', 'CARD', 'NETBANK', 'WALLET', 'upi', 'card', 'netbank', 'wallet'])
  payment_method?: string;

  @ApiProperty({
    description: 'Client or gateway payment reference, if already available',
    required: false,
    example: 'PGR20260503001',
  })
  @IsOptional()
  @IsString()
  payment_gateway_ref?: string;

  @ApiProperty({
    description: 'Client idempotency key, if already generated by the UI/payment layer',
    required: false,
    example: 'idem-checkout-20260503-001',
  })
  @IsOptional()
  @IsString()
  idempotency_key?: string;
}
